INCLUDES += -I$(PKGDIRBASE)/dcaf/include

ifneq (,$(filter libcoap_tinydtls,$(USEMODULE)))
  CFLAGS += -DCOAP_DTLS_TINYDTLS
endif

#ifeq ($(TOOLCHAIN), llvm)
#  CFLAGS += -Wno-gnu-zero-variadic-macro-arguments -Wno-unused-function
#endif
