PKG_NAME=dcaf
PKG_URL=git@gitlab.informatik.uni-bremen.de:DCAF/dcaf.git
PKG_VERSION=cf58135d3931a50bacdf6fa587dfb63bf976ee80
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_BUILDDIR)/src -f $(CURDIR)/Makefile.dcaf
